version: "3"
services:
  app:
    build: ./
    links:
      - db
    ports:
      - "3005:3005"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./bd/dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jack_api_hacienda